"""empty message

Revision ID: 2daa5af46bae
Revises: 295cbf8a4e1d
Create Date: 2017-10-20 22:47:56.699028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2daa5af46bae'
down_revision = '295cbf8a4e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastname', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lastname')
    # ### end Alembic commands ###
