"""empty message

Revision ID: f0ccd8a0ca8f
Revises: e68b69b7ff80
Create Date: 2017-10-20 23:16:57.331470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ccd8a0ca8f'
down_revision = 'e68b69b7ff80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastname', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lastname')
    # ### end Alembic commands ###
